import js from '@eslint/js'
import prettier from 'eslint-config-prettier'
import astro from 'eslint-plugin-astro'
import solid from 'eslint-plugin-solid'
import globals from 'globals'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    ignores: [
      '.astro/**',
      '.hulla/.cache/**',
      'dist/**',
      'node_modules/**',
      'output/**',
      'public/pagefind/**',
      'src/env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...astro.configs['flat/recommended'],
  {
    files: ['**/*.tsx'],
    plugins: { solid },
    rules: solid.configs.typescript.rules,
  },
  {
    files: [
      'src/components/button/**/*.tsx',
      'src/components/command/**/*.tsx',
      'src/components/dialog/**/*.tsx',
      'src/components/input/**/*.tsx',
      'src/components/spinner/**/*.tsx',
    ],
    rules: {
      // Generated by @hulla/ui and linted in its source repository.
      'solid/reactivity': 'off',
    },
  },
  {
    files: ['**/*.{js,mjs,ts,tsx,astro}'],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },
  prettier
)
